discord:
  token: token_here
  test_token: 79980b00893b8ff80105aa5ab288f443d3019984221bb26c0eb299fca3a44342

enviro: "test"

supercell:
  user: sgtmajorjay@gmail.com
  pass: !soXyCa3oTG_7rGGYEH9g!!F-iDwjT*2

email:
  address: hogrider@email.com
  password: hog_rider_email_password

guild:
  bot_logs: guild_ids
  junkies: guild_ids

category:
  bot_demo: category_id

channels:
  admin: channel_id
  general: channel_id
  mod-log: channel_id
  logs: channel_id
  forum-poster: channel_id
  rules: channel_id
  welcome: channel_id
  lanugage_roles: channel_id
  projects: channel_id
  api_response: channel_id
  testing: channel_id

roles:
  admin: role_id
  developer: role_id
  bots: role_id
  hog_rider: role_id
  vip_guest: role_id
  temp_guest: role_id
  everyone: role_id

pg:
  uri: postgresql://user:password@host:5432

bots:
  rcs: bot_user_id
  cr: bot_user_id
  dt: bot_user_id
  karen: bot_user_id
  maniacs: bot_user_id
  minion: bot_user_id
  oak: bot_user_id
  wiz: bot_user_id
  wm: bot_user_id
  clashcord: bot_user_id
  sk: bot_user_id
  bat: bot_user_id
  clashperk: bot_user_id
  ivory: bot_user_id
  alph4: bot_user_id
